Mar 952 an authnentication broker
uktrade/market-access-api pull request #286
Opened 2021-05-07 10:10 UTC by cad106uk

2021-05-07 10:47 UTC, rossmiller requested changes
Looks good. I've made some suggestions.

2021-05-07 10:47 UTC, rossmiller commented on api/user/backend.py
> +            profile_obj.user.is_active = True
Why are you setting is_staff and is_active here?

2021-05-07 10:47 UTC, rossmiller commented on api/user/backend.py
> +            profile_obj.sso_user_id = raw_profile["user_id"]
Could we call it "profile" rather than "profile_obj"?

2021-05-07 10:47 UTC, rossmiller commented on api/user/backend.py
> +        def _build_profile(profile_obj):
This would be better as a function of the class

2021-05-07 12:19 UTC, cad106uk commented on api/user/backend.py
> +        def _build_profile(profile_obj):
Hmm, well, this is never meant to be used anywhere else or by anyone else, which is why I use an inline function.

Personal whenever I see a static method I always think "this should be a function". The only reason I can think of to use a static method is when you cannot know where the class in going to be imported. Personally, I would be happier if both these methods where functions.

I have made the change you asked for, I just grumbled a bit about it.

2021-05-10 10:35 UTC, jamespacileo approved these changes

2021-05-10 11:08 UTC, rossmiller approved these changes
LGTM!

2021-05-10 11:10 UTC, merged