lint fix
uktrade/market-access-api pull request #544
Opened 2023-07-18 11:20 UTC by osimuka

2023-07-19 13:30 UTC, chris-pettinga requested changes

2023-07-19 13:30 UTC, chris-pettinga commented on api/barriers/serializers/data_workspace.py
> +    main_sector = serializers.SerializerMethodField()
Can we not use the SectorsField that Feroze created

2023-07-19 14:14 UTC, osimuka commented on api/barriers/serializers/data_workspace.py
> +    main_sector = serializers.SerializerMethodField()
Yes, but I will be looking for the string name itself, I have adjusted the method to use `SectorField` thanks for pointing it out.
The dataworkspace is looking for a string or None in that field

2023-07-19 14:17 UTC, chris-pettinga commented on api/barriers/serializers/data_workspace.py
> +    main_sector = serializers.SerializerMethodField()
got you, didn't realise this was specifically the DataWorkspaceSerializer

2023-07-19 14:19 UTC, osimuka commented on api/barriers/serializers/data_workspace.py
> +    main_sector = serializers.SerializerMethodField()
No worries, but the pointers helped very well thanks

2023-07-19 14:22 UTC, chris-pettinga commented on api/barriers/serializers/data_workspace.py
> +    def get_export_types(self, instance) -> typing.List[str]:
don't need this method if export_types is now a ExportTypes field

2023-07-19 14:30 UTC, ferozerub approved these changes

2023-07-20 08:53 UTC, chris-pettinga approved these changes

2023-07-20 08:56 UTC, merged