added main sector only
uktrade/market-access-api pull request #579
Opened 2023-09-11 08:32 UTC by osimuka

2023-09-11 11:53 UTC, chris-pettinga requested changes

2023-09-11 11:53 UTC, chris-pettinga commented on tests/barriers/test_list_barriers.py
> +        assert response.data["count"] == 1
can we add a new test confirming that if we make a request with another sector ID (that is not the barriers main sector), the API returns 0 results?

2023-09-11 12:00 UTC, osimuka commented on tests/barriers/test_list_barriers.py
> +        assert response.data["count"] == 1
Nice, added the new test case

2023-09-12 13:26 UTC, chris-pettinga requested changes

2023-09-12 13:26 UTC, chris-pettinga commented on api/barriers/models.py
> +        return queryset.filter(base_query | Q(sectors__overlap=value)).distinct()
I think we can remove the .distinct() call here as Feroze's ticket should've resolved these duplicates
```suggestion
        return queryset.filter(base_query | Q(sectors__overlap=value))
```

2023-09-12 13:26 UTC, chris-pettinga commented on api/barriers/models.py
> +            return queryset.filter(base_query).distinct()
Same as here
```suggestion
            return queryset.filter(base_query)
```

2023-09-12 13:26 UTC, chris-pettinga commented on api/barriers/models.py
> +        only_main_sector = self.data.get("only_main_sector", "no")
for consistency, I think this should also default to False, then we don't need to check for `only_main_sector == "yes"`, we can just do `if only_main_sector`

2023-09-12 13:26 UTC, chris-pettinga commented on api/barriers/models.py
> +            return queryset.filter(main_sector__isnull=False).distinct()
remove .distinct()
```suggestion
            return queryset.filter(main_sector__isnull=False)
```

2023-09-13 09:22 UTC, chris-pettinga approved these changes

2023-09-13 09:34 UTC, ferozerub approved these changes

2023-09-15 13:37 UTC, merged