TSS-982: Add Priority Level to history
uktrade/market-access-api pull request #634
Opened 2023-11-01 13:01 UTC by abarolo

2023-11-01 13:02 UTC, chris-pettinga commented on api/history/items/barriers.py
> +from ...metadata.constants import PRIORITY_LEVELS
I know the relative ... imports have been around since before this PR, but I think they're ugly and importantly liable to fail. Would you mind refactoring them so they're more explicit? Thanks

2023-11-01 13:03 UTC, chris-pettinga requested changes

2023-11-01 13:03 UTC, chris-pettinga commented on api/history/items/barriers.py
> +        return PRIORITY_LEVELS._display_map.get(record.priority_level, "")
can you use record.get_priority_level_display() here instead?

```suggestion
        return record.get_priority_level_display()
```

2023-11-01 13:15 UTC, chris-pettinga approved these changes

2023-11-02 11:31 UTC, ferozerub approved these changes

2023-11-02 13:09 UTC, osimuka approved these changes

2023-11-02 13:43 UTC, merged