Feature/tss 1093/review access control
uktrade/market-access-api pull request #640
Opened 2023-11-07 15:55 UTC by ferozerub

2023-11-07 16:25 UTC, chris-pettinga requested changes

2023-11-07 16:25 UTC, chris-pettinga commented on tests/feedback/test_views.py
> +        self.api_client2 = self.create_api_client(user=self.user2)
Looks like we don't use this further on down?

2023-11-08 11:09 UTC, chris-pettinga approved these changes

2023-11-08 11:12 UTC, ferozerub commented on tests/feedback/test_views.py
> +        self.api_client2 = self.create_api_client(user=self.user2)
Agreed - removed the second api client

2023-11-08 14:39 UTC, osimuka commented on api/core/permissions.py
> +        if request.method in SAFE_METHODS:
if this is a get request, in DRF which is also `retrieve` & `list` it will return True

2023-11-08 14:40 UTC, Santino-Trade approved these changes

2023-11-08 14:40 UTC, osimuka commented on api/core/permissions.py
> +        if request.method in SAFE_METHODS:
is this what we want here?

2023-11-08 14:42 UTC, osimuka approved these changes

2023-11-08 14:50 UTC, merged