TSS-958: History V2 POC
uktrade/market-access-api pull request #647
Opened 2023-11-19 00:20 UTC by abarolo

The barrier history application is over-engineered and scales inefficiently. 

Query Complexity: ~O(n*m*x) 

n = # historical tables
m = # items
x = # item related lookups

Below is a screenshot of a barrier with ~20 historical items on separate tables.

<img width="757" alt="Screenshot 2023-11-18 at 23 45 19" src="https://github.com/uktrade/market-access-api/assets/145478290/6d05cf14-84cb-4443-a2bb-644b67a3b207">

This is a POC of working functionality backwards compatible with the legacy implementation.

Once all historical components are fully refactored:

Query Complexity = O(n)

n = # historical tables

2023-11-24 15:36 UTC, ferozerub approved these changes

2023-11-24 16:18 UTC, chris-pettinga requested changes

2023-11-24 16:18 UTC, chris-pettinga commented on tests/history/factories.py
> +class BarrierFactory(factory.django.DjangoModelFactory):
We already have a BarrierFactory here - https://github.com/uktrade/market-access-api/blob/588198500a067b78230b492de3e4425f7f8163ca/tests/barriers/factories.py#L78

2023-11-24 16:48 UTC, abarolo commented on tests/history/factories.py
> +class BarrierFactory(factory.django.DjangoModelFactory):
Yes I got it from here and removed parts of it. Just trying to maintain as much separation for now while doing the refactor.

2023-11-27 10:22 UTC, chris-pettinga commented on tests/history/factories.py
> +class BarrierFactory(factory.django.DjangoModelFactory):
ok happy with this as long as you keep track of all the additional code infrastructure the refactor needs, so we're able to quickly delete all of it/all of the old stuff when we do the absolute switchover.

2023-11-27 10:22 UTC, chris-pettinga approved these changes

2023-11-27 10:33 UTC, abarolo commented on tests/history/factories.py
> +class BarrierFactory(factory.django.DjangoModelFactory):
of coourse

2023-11-27 10:39 UTC, merged