feature/TSS-1365-refactor-history-endpoints-v2-part3-v2
uktrade/market-access-api pull request #684
Opened 2023-12-14 14:08 UTC by osimuka

2023-12-18 18:13 UTC, chris-pettinga requested changes
Let's talk through tomorrow after SU

2023-12-18 18:13 UTC, chris-pettinga commented on api/history/v2/enrichment.py
> +                "is_resolved": is_resolved(str(value["status"])),
why is `is_resolved` in its own function?

2023-12-18 18:13 UTC, chris-pettinga commented on api/history/v2/service.py
> +        or [] + public_barrier_notes_history
I'm not sure I understand the `or` here, let's talk through tomorrow

2023-12-18 18:13 UTC, chris-pettinga commented on api/collaboration/models.py
> +    def get_history(cls, barrier_id, start_date=None):
The other `get_history` methods do not implement the `start_date` argument, am I missing something?

2023-12-19 09:55 UTC, Santino-Trade commented on api/collaboration/models.py
> +        from api.history.v2.service import get_model_history
I came across this too on the Interaction model, but I imported
```python
from api.history.v2 import service
``` 
at the top in the imports and used 
```python
return service.get_model_history(
            qs,
            model="note",
            fields=fields,
            track_first_item=True,
        )
```
in the get_history method. Its a bit neater to keep imports all in their own zone, so i'd say give it a go to see if it works this way for public barriers.

2023-12-19 10:04 UTC, Santino-Trade commented on api/collaboration/models.py
> +    def get_history(cls, barrier_id, start_date=None):
Following it back, it's used to limit the results to everything after the barriers 'reported_on' date. Not sure how that will change your result, but its possible that when the object is created it creates a bunch of empty changes that go from None -> "" or []. I reckon its worth exploring if we can cut it all out.

2023-12-19 10:54 UTC, chris-pettinga requested changes

2023-12-19 10:54 UTC, chris-pettinga commented on api/collaboration/models.py
> +            if start_date
remove start_date logic and just keep `track_first_time`

2023-12-19 10:54 UTC, chris-pettinga commented on api/history/manager.py
> +            else TeamMember.get_history(barrier_id=barrier.pk)
just keep this line as per above

2023-12-19 10:54 UTC, chris-pettinga commented on api/history/manager.py
> +            barrier_id=barrier.pk, start_date=start_date
remove start_date from here and make sure `track_first_item` is true

2023-12-19 10:54 UTC, chris-pettinga commented on api/history/manager.py
> +            if ignore_creation_items:
the value of `track_first_item` should be equal to the opposite of the value of `ignore_created_items`

2023-12-19 10:54 UTC, chris-pettinga commented on api/history/v2/enrichment.py
> +                "is_resolved": is_resolved(str(value["status"])),
```suggestion
                "is_resolved": str(value["status"] == BarrierStatus.RESOLVED_IN_FULL,
```

2023-12-19 10:54 UTC, chris-pettinga commented on api/history/v2/enrichment.py
> +            user = user_model.objects.filter(id=value).first()
```suggestion
            user = user_model.objects.get(id=value)
```

2023-12-19 10:54 UTC, chris-pettinga commented on api/interactions/models.py
> +    def get_history(cls, barrier_id, start_date=None):
can remove start_date

2023-12-19 10:54 UTC, chris-pettinga commented on api/interactions/models.py
> +        )
add `track_first_item`

2023-12-19 10:54 UTC, chris-pettinga commented on api/wto/models.py
> +    def get_history(cls, barrier_id, start_date=None):
same as above

2023-12-19 11:45 UTC, Santino-Trade approved these changes

2023-12-20 09:11 UTC, Santino-Trade approved these changes

2023-12-20 09:25 UTC, chris-pettinga approved these changes

2023-12-20 09:41 UTC, merged